// Code generated by ent, DO NOT EDIT.

package issueforent

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the issueforent type in the database.
	Label = "issue_for_ent"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// EdgeRepository holds the string denoting the repository edge name in mutations.
	EdgeRepository = "repository"
	// Table holds the table name of the issueforent in the database.
	Table = "issue_for_ents"
	// RepositoryTable is the table that holds the repository relation/edge.
	RepositoryTable = "issue_for_ents"
	// RepositoryInverseTable is the table name for the RepositoryForEnt entity.
	// It exists in this package in order to avoid circular dependency with the "repositoryforent" package.
	RepositoryInverseTable = "repository_for_ents"
	// RepositoryColumn is the table column denoting the repository relation/edge.
	RepositoryColumn = "repository_for_ent_issue_for_ents"
)

// Columns holds all SQL columns for issueforent fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "issue_for_ents"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"repository_for_ent_issue_for_ents",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the IssueForEnt queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRepositoryField orders the results by repository field.
func ByRepositoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRepositoryStep(), sql.OrderByField(field, opts...))
	}
}
func newRepositoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RepositoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RepositoryTable, RepositoryColumn),
	)
}
