// Code generated by ent, DO NOT EDIT.

package issueforent

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/common-library/go/database/orm/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.IssueForEnt {
	return predicate.IssueForEnt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.IssueForEnt {
	return predicate.IssueForEnt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.IssueForEnt {
	return predicate.IssueForEnt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.IssueForEnt {
	return predicate.IssueForEnt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.IssueForEnt {
	return predicate.IssueForEnt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.IssueForEnt {
	return predicate.IssueForEnt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.IssueForEnt {
	return predicate.IssueForEnt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.IssueForEnt {
	return predicate.IssueForEnt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.IssueForEnt {
	return predicate.IssueForEnt(sql.FieldLTE(FieldID, id))
}

// HasRepository applies the HasEdge predicate on the "repository" edge.
func HasRepository() predicate.IssueForEnt {
	return predicate.IssueForEnt(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RepositoryTable, RepositoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRepositoryWith applies the HasEdge predicate on the "repository" edge with a given conditions (other predicates).
func HasRepositoryWith(preds ...predicate.RepositoryForEnt) predicate.IssueForEnt {
	return predicate.IssueForEnt(func(s *sql.Selector) {
		step := newRepositoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IssueForEnt) predicate.IssueForEnt {
	return predicate.IssueForEnt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IssueForEnt) predicate.IssueForEnt {
	return predicate.IssueForEnt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IssueForEnt) predicate.IssueForEnt {
	return predicate.IssueForEnt(sql.NotPredicates(p))
}
