// Code generated by ent, DO NOT EDIT.

package userforent

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/common-library/go/database/orm/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserForEnt {
	return predicate.UserForEnt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserForEnt {
	return predicate.UserForEnt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserForEnt {
	return predicate.UserForEnt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserForEnt {
	return predicate.UserForEnt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserForEnt {
	return predicate.UserForEnt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserForEnt {
	return predicate.UserForEnt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserForEnt {
	return predicate.UserForEnt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserForEnt {
	return predicate.UserForEnt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserForEnt {
	return predicate.UserForEnt(sql.FieldLTE(FieldID, id))
}

// HasRepositoryForEnts applies the HasEdge predicate on the "repository_for_ents" edge.
func HasRepositoryForEnts() predicate.UserForEnt {
	return predicate.UserForEnt(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, RepositoryForEntsTable, RepositoryForEntsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRepositoryForEntsWith applies the HasEdge predicate on the "repository_for_ents" edge with a given conditions (other predicates).
func HasRepositoryForEntsWith(preds ...predicate.RepositoryForEnt) predicate.UserForEnt {
	return predicate.UserForEnt(func(s *sql.Selector) {
		step := newRepositoryForEntsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserForEnt) predicate.UserForEnt {
	return predicate.UserForEnt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserForEnt) predicate.UserForEnt {
	return predicate.UserForEnt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserForEnt) predicate.UserForEnt {
	return predicate.UserForEnt(sql.NotPredicates(p))
}
