// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: src/github.com/heaven-chp/common-library-go/grpc/sample/sample.proto

package sample

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data1 int64  `protobuf:"varint,1,opt,name=data1,proto3" json:"data1,omitempty"`
	Data2 string `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetData1() int64 {
	if x != nil {
		return x.Data1
	}
	return 0
}

func (x *Request) GetData2() string {
	if x != nil {
		return x.Data2
	}
	return ""
}

type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data1 int64  `protobuf:"varint,1,opt,name=data1,proto3" json:"data1,omitempty"`
	Data2 string `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetData1() int64 {
	if x != nil {
		return x.Data1
	}
	return 0
}

func (x *Reply) GetData2() string {
	if x != nil {
		return x.Data2
	}
	return ""
}

var File_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto protoreflect.FileDescriptor

var file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_rawDesc = []byte{
	0x0a, 0x44, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x68, 0x65, 0x61, 0x76, 0x65, 0x6e, 0x2d, 0x63, 0x68, 0x70, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2d, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2d, 0x67, 0x6f, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x32,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x32, 0x22, 0x33, 0x0a,
	0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x31, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x31, 0x12, 0x14, 0x0a, 0x05,
	0x64, 0x61, 0x74, 0x61, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61, 0x74,
	0x61, 0x32, 0x32, 0x24, 0x0a, 0x06, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x04,
	0x46, 0x75, 0x6e, 0x63, 0x12, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06,
	0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_rawDescOnce sync.Once
	file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_rawDescData = file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_rawDesc
)

func file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_rawDescGZIP() []byte {
	file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_rawDescOnce.Do(func() {
		file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_rawDescData)
	})
	return file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_rawDescData
}

var file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_goTypes = []interface{}{
	(*Request)(nil), // 0: Request
	(*Reply)(nil),   // 1: Reply
}
var file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_depIdxs = []int32{
	0, // 0: Sample.Func:input_type -> Request
	1, // 1: Sample.Func:output_type -> Reply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_init() }
func file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_init() {
	if File_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_goTypes,
		DependencyIndexes: file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_depIdxs,
		MessageInfos:      file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_msgTypes,
	}.Build()
	File_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto = out.File
	file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_rawDesc = nil
	file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_goTypes = nil
	file_src_github_com_heaven_chp_common_library_go_grpc_sample_sample_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SampleClient is the client API for Sample service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SampleClient interface {
	Func(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type sampleClient struct {
	cc grpc.ClientConnInterface
}

func NewSampleClient(cc grpc.ClientConnInterface) SampleClient {
	return &sampleClient{cc}
}

func (c *sampleClient) Func(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/Sample/Func", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SampleServer is the server API for Sample service.
type SampleServer interface {
	Func(context.Context, *Request) (*Reply, error)
}

// UnimplementedSampleServer can be embedded to have forward compatible implementations.
type UnimplementedSampleServer struct {
}

func (*UnimplementedSampleServer) Func(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Func not implemented")
}

func RegisterSampleServer(s *grpc.Server, srv SampleServer) {
	s.RegisterService(&_Sample_serviceDesc, srv)
}

func _Sample_Func_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleServer).Func(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Sample/Func",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleServer).Func(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sample_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Sample",
	HandlerType: (*SampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Func",
			Handler:    _Sample_Func_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/github.com/heaven-chp/common-library-go/grpc/sample/sample.proto",
}
