// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: grpc/sample/sample.proto

package sample

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data1         int64                  `protobuf:"varint,1,opt,name=data1,proto3" json:"data1,omitempty"`
	Data2         string                 `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_grpc_sample_sample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_sample_sample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_grpc_sample_sample_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetData1() int64 {
	if x != nil {
		return x.Data1
	}
	return 0
}

func (x *Request) GetData2() string {
	if x != nil {
		return x.Data2
	}
	return ""
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data1         int64                  `protobuf:"varint,1,opt,name=data1,proto3" json:"data1,omitempty"`
	Data2         string                 `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_grpc_sample_sample_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_sample_sample_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_grpc_sample_sample_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetData1() int64 {
	if x != nil {
		return x.Data1
	}
	return 0
}

func (x *Reply) GetData2() string {
	if x != nil {
		return x.Data2
	}
	return ""
}

var File_grpc_sample_sample_proto protoreflect.FileDescriptor

const file_grpc_sample_sample_proto_rawDesc = "" +
	"\n" +
	"\x18grpc/sample/sample.proto\"5\n" +
	"\aRequest\x12\x14\n" +
	"\x05data1\x18\x01 \x01(\x03R\x05data1\x12\x14\n" +
	"\x05data2\x18\x02 \x01(\tR\x05data2\"3\n" +
	"\x05Reply\x12\x14\n" +
	"\x05data1\x18\x01 \x01(\x03R\x05data1\x12\x14\n" +
	"\x05data2\x18\x02 \x01(\tR\x05data22F\n" +
	"\x06Sample\x12\x1b\n" +
	"\x05Func1\x12\b.Request\x1a\x06.Reply\"\x00\x12\x1f\n" +
	"\x05Func2\x12\b.Request\x1a\x06.Reply\"\x00(\x010\x01B\n" +
	"Z\b.;sampleb\x06proto3"

var (
	file_grpc_sample_sample_proto_rawDescOnce sync.Once
	file_grpc_sample_sample_proto_rawDescData []byte
)

func file_grpc_sample_sample_proto_rawDescGZIP() []byte {
	file_grpc_sample_sample_proto_rawDescOnce.Do(func() {
		file_grpc_sample_sample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_sample_sample_proto_rawDesc), len(file_grpc_sample_sample_proto_rawDesc)))
	})
	return file_grpc_sample_sample_proto_rawDescData
}

var file_grpc_sample_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_sample_sample_proto_goTypes = []any{
	(*Request)(nil), // 0: Request
	(*Reply)(nil),   // 1: Reply
}
var file_grpc_sample_sample_proto_depIdxs = []int32{
	0, // 0: Sample.Func1:input_type -> Request
	0, // 1: Sample.Func2:input_type -> Request
	1, // 2: Sample.Func1:output_type -> Reply
	1, // 3: Sample.Func2:output_type -> Reply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_sample_sample_proto_init() }
func file_grpc_sample_sample_proto_init() {
	if File_grpc_sample_sample_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_sample_sample_proto_rawDesc), len(file_grpc_sample_sample_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_sample_sample_proto_goTypes,
		DependencyIndexes: file_grpc_sample_sample_proto_depIdxs,
		MessageInfos:      file_grpc_sample_sample_proto_msgTypes,
	}.Build()
	File_grpc_sample_sample_proto = out.File
	file_grpc_sample_sample_proto_goTypes = nil
	file_grpc_sample_sample_proto_depIdxs = nil
}
