// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: mysql.sql

package pkg

import (
	"context"
	"database/sql"
)

const createTable01 = `-- name: CreateTable01 :exec
CREATE TABLE IF NOT EXISTS table01_for_mysql (
  field01 VARCHAR(64) PRIMARY KEY,
  field02 BIGINT NOT NULL
)
`

func (q *Queries) CreateTable01(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createTable01)
	return err
}

const deleteTable01 = `-- name: DeleteTable01 :exec
DELETE FROM table01_for_mysql WHERE field01 = ?
`

func (q *Queries) DeleteTable01(ctx context.Context, field01 string) error {
	_, err := q.db.ExecContext(ctx, deleteTable01, field01)
	return err
}

const dropTable01 = `-- name: DropTable01 :exec
DROP TABLE IF EXISTS table01_for_mysql
`

func (q *Queries) DropTable01(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, dropTable01)
	return err
}

const getTable01 = `-- name: GetTable01 :one
SELECT field01, field02 FROM table01_for_mysql WHERE field01 = ?
`

func (q *Queries) GetTable01(ctx context.Context, field01 string) (Table01ForMysql, error) {
	row := q.db.QueryRowContext(ctx, getTable01, field01)
	var i Table01ForMysql
	err := row.Scan(&i.Field01, &i.Field02)
	return i, err
}

const insertTable01 = `-- name: InsertTable01 :execresult
INSERT INTO table01_for_mysql(field01, field02) VALUES(?, ?)
`

type InsertTable01Params struct {
	Field01 string
	Field02 int64
}

func (q *Queries) InsertTable01(ctx context.Context, arg InsertTable01Params) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertTable01, arg.Field01, arg.Field02)
}

const listTable01 = `-- name: ListTable01 :many
SELECT field01, field02 FROM table01_for_mysql ORDER BY field01
`

func (q *Queries) ListTable01(ctx context.Context) ([]Table01ForMysql, error) {
	rows, err := q.db.QueryContext(ctx, listTable01)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Table01ForMysql
	for rows.Next() {
		var i Table01ForMysql
		if err := rows.Scan(&i.Field01, &i.Field02); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTable01 = `-- name: UpdateTable01 :exec
UPDATE table01_for_mysql set field02 = ? WHERE field01 = ?
`

type UpdateTable01Params struct {
	Field02 int64
	Field01 string
}

func (q *Queries) UpdateTable01(ctx context.Context, arg UpdateTable01Params) error {
	_, err := q.db.ExecContext(ctx, updateTable01, arg.Field02, arg.Field01)
	return err
}
