// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// IssueForEnt is the predicate function for issueforent builders.
type IssueForEnt func(*sql.Selector)

// RepositoryForEnt is the predicate function for repositoryforent builders.
type RepositoryForEnt func(*sql.Selector)

// Table01ForEnt is the predicate function for table01forent builders.
type Table01ForEnt func(*sql.Selector)

// UserForEnt is the predicate function for userforent builders.
type UserForEnt func(*sql.Selector)
