// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/common-library/go/database/orm/ent/issueforent"
	"github.com/common-library/go/database/orm/ent/predicate"
)

// IssueForEntDelete is the builder for deleting a IssueForEnt entity.
type IssueForEntDelete struct {
	config
	hooks    []Hook
	mutation *IssueForEntMutation
}

// Where appends a list predicates to the IssueForEntDelete builder.
func (ifed *IssueForEntDelete) Where(ps ...predicate.IssueForEnt) *IssueForEntDelete {
	ifed.mutation.Where(ps...)
	return ifed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ifed *IssueForEntDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ifed.sqlExec, ifed.mutation, ifed.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ifed *IssueForEntDelete) ExecX(ctx context.Context) int {
	n, err := ifed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ifed *IssueForEntDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(issueforent.Table, sqlgraph.NewFieldSpec(issueforent.FieldID, field.TypeInt))
	if ps := ifed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ifed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ifed.mutation.done = true
	return affected, err
}

// IssueForEntDeleteOne is the builder for deleting a single IssueForEnt entity.
type IssueForEntDeleteOne struct {
	ifed *IssueForEntDelete
}

// Where appends a list predicates to the IssueForEntDelete builder.
func (ifedo *IssueForEntDeleteOne) Where(ps ...predicate.IssueForEnt) *IssueForEntDeleteOne {
	ifedo.ifed.mutation.Where(ps...)
	return ifedo
}

// Exec executes the deletion query.
func (ifedo *IssueForEntDeleteOne) Exec(ctx context.Context) error {
	n, err := ifedo.ifed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{issueforent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ifedo *IssueForEntDeleteOne) ExecX(ctx context.Context) {
	if err := ifedo.Exec(ctx); err != nil {
		panic(err)
	}
}
