// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/common-library/go/database/orm/ent/predicate"
	"github.com/common-library/go/database/orm/ent/table01forent"
)

// Table01ForEntQuery is the builder for querying Table01ForEnt entities.
type Table01ForEntQuery struct {
	config
	ctx        *QueryContext
	order      []table01forent.OrderOption
	inters     []Interceptor
	predicates []predicate.Table01ForEnt
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the Table01ForEntQuery builder.
func (teq *Table01ForEntQuery) Where(ps ...predicate.Table01ForEnt) *Table01ForEntQuery {
	teq.predicates = append(teq.predicates, ps...)
	return teq
}

// Limit the number of records to be returned by this query.
func (teq *Table01ForEntQuery) Limit(limit int) *Table01ForEntQuery {
	teq.ctx.Limit = &limit
	return teq
}

// Offset to start from.
func (teq *Table01ForEntQuery) Offset(offset int) *Table01ForEntQuery {
	teq.ctx.Offset = &offset
	return teq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (teq *Table01ForEntQuery) Unique(unique bool) *Table01ForEntQuery {
	teq.ctx.Unique = &unique
	return teq
}

// Order specifies how the records should be ordered.
func (teq *Table01ForEntQuery) Order(o ...table01forent.OrderOption) *Table01ForEntQuery {
	teq.order = append(teq.order, o...)
	return teq
}

// First returns the first Table01ForEnt entity from the query.
// Returns a *NotFoundError when no Table01ForEnt was found.
func (teq *Table01ForEntQuery) First(ctx context.Context) (*Table01ForEnt, error) {
	nodes, err := teq.Limit(1).All(setContextOp(ctx, teq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{table01forent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (teq *Table01ForEntQuery) FirstX(ctx context.Context) *Table01ForEnt {
	node, err := teq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Table01ForEnt ID from the query.
// Returns a *NotFoundError when no Table01ForEnt ID was found.
func (teq *Table01ForEntQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = teq.Limit(1).IDs(setContextOp(ctx, teq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{table01forent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (teq *Table01ForEntQuery) FirstIDX(ctx context.Context) int {
	id, err := teq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Table01ForEnt entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Table01ForEnt entity is found.
// Returns a *NotFoundError when no Table01ForEnt entities are found.
func (teq *Table01ForEntQuery) Only(ctx context.Context) (*Table01ForEnt, error) {
	nodes, err := teq.Limit(2).All(setContextOp(ctx, teq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{table01forent.Label}
	default:
		return nil, &NotSingularError{table01forent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (teq *Table01ForEntQuery) OnlyX(ctx context.Context) *Table01ForEnt {
	node, err := teq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Table01ForEnt ID in the query.
// Returns a *NotSingularError when more than one Table01ForEnt ID is found.
// Returns a *NotFoundError when no entities are found.
func (teq *Table01ForEntQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = teq.Limit(2).IDs(setContextOp(ctx, teq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{table01forent.Label}
	default:
		err = &NotSingularError{table01forent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (teq *Table01ForEntQuery) OnlyIDX(ctx context.Context) int {
	id, err := teq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Table01ForEnts.
func (teq *Table01ForEntQuery) All(ctx context.Context) ([]*Table01ForEnt, error) {
	ctx = setContextOp(ctx, teq.ctx, ent.OpQueryAll)
	if err := teq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Table01ForEnt, *Table01ForEntQuery]()
	return withInterceptors[[]*Table01ForEnt](ctx, teq, qr, teq.inters)
}

// AllX is like All, but panics if an error occurs.
func (teq *Table01ForEntQuery) AllX(ctx context.Context) []*Table01ForEnt {
	nodes, err := teq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Table01ForEnt IDs.
func (teq *Table01ForEntQuery) IDs(ctx context.Context) (ids []int, err error) {
	if teq.ctx.Unique == nil && teq.path != nil {
		teq.Unique(true)
	}
	ctx = setContextOp(ctx, teq.ctx, ent.OpQueryIDs)
	if err = teq.Select(table01forent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (teq *Table01ForEntQuery) IDsX(ctx context.Context) []int {
	ids, err := teq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (teq *Table01ForEntQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, teq.ctx, ent.OpQueryCount)
	if err := teq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, teq, querierCount[*Table01ForEntQuery](), teq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (teq *Table01ForEntQuery) CountX(ctx context.Context) int {
	count, err := teq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (teq *Table01ForEntQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, teq.ctx, ent.OpQueryExist)
	switch _, err := teq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (teq *Table01ForEntQuery) ExistX(ctx context.Context) bool {
	exist, err := teq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the Table01ForEntQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (teq *Table01ForEntQuery) Clone() *Table01ForEntQuery {
	if teq == nil {
		return nil
	}
	return &Table01ForEntQuery{
		config:     teq.config,
		ctx:        teq.ctx.Clone(),
		order:      append([]table01forent.OrderOption{}, teq.order...),
		inters:     append([]Interceptor{}, teq.inters...),
		predicates: append([]predicate.Table01ForEnt{}, teq.predicates...),
		// clone intermediate query.
		sql:  teq.sql.Clone(),
		path: teq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CommonField01 int `json:"common_field01,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Table01ForEnt.Query().
//		GroupBy(table01forent.FieldCommonField01).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (teq *Table01ForEntQuery) GroupBy(field string, fields ...string) *Table01ForEntGroupBy {
	teq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &Table01ForEntGroupBy{build: teq}
	grbuild.flds = &teq.ctx.Fields
	grbuild.label = table01forent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CommonField01 int `json:"common_field01,omitempty"`
//	}
//
//	client.Table01ForEnt.Query().
//		Select(table01forent.FieldCommonField01).
//		Scan(ctx, &v)
func (teq *Table01ForEntQuery) Select(fields ...string) *Table01ForEntSelect {
	teq.ctx.Fields = append(teq.ctx.Fields, fields...)
	sbuild := &Table01ForEntSelect{Table01ForEntQuery: teq}
	sbuild.label = table01forent.Label
	sbuild.flds, sbuild.scan = &teq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a Table01ForEntSelect configured with the given aggregations.
func (teq *Table01ForEntQuery) Aggregate(fns ...AggregateFunc) *Table01ForEntSelect {
	return teq.Select().Aggregate(fns...)
}

func (teq *Table01ForEntQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range teq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, teq); err != nil {
				return err
			}
		}
	}
	for _, f := range teq.ctx.Fields {
		if !table01forent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if teq.path != nil {
		prev, err := teq.path(ctx)
		if err != nil {
			return err
		}
		teq.sql = prev
	}
	return nil
}

func (teq *Table01ForEntQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Table01ForEnt, error) {
	var (
		nodes = []*Table01ForEnt{}
		_spec = teq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Table01ForEnt).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Table01ForEnt{config: teq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, teq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (teq *Table01ForEntQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := teq.querySpec()
	_spec.Node.Columns = teq.ctx.Fields
	if len(teq.ctx.Fields) > 0 {
		_spec.Unique = teq.ctx.Unique != nil && *teq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, teq.driver, _spec)
}

func (teq *Table01ForEntQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(table01forent.Table, table01forent.Columns, sqlgraph.NewFieldSpec(table01forent.FieldID, field.TypeInt))
	_spec.From = teq.sql
	if unique := teq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if teq.path != nil {
		_spec.Unique = true
	}
	if fields := teq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, table01forent.FieldID)
		for i := range fields {
			if fields[i] != table01forent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := teq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := teq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := teq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := teq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (teq *Table01ForEntQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(teq.driver.Dialect())
	t1 := builder.Table(table01forent.Table)
	columns := teq.ctx.Fields
	if len(columns) == 0 {
		columns = table01forent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if teq.sql != nil {
		selector = teq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if teq.ctx.Unique != nil && *teq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range teq.predicates {
		p(selector)
	}
	for _, p := range teq.order {
		p(selector)
	}
	if offset := teq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := teq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Table01ForEntGroupBy is the group-by builder for Table01ForEnt entities.
type Table01ForEntGroupBy struct {
	selector
	build *Table01ForEntQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tegb *Table01ForEntGroupBy) Aggregate(fns ...AggregateFunc) *Table01ForEntGroupBy {
	tegb.fns = append(tegb.fns, fns...)
	return tegb
}

// Scan applies the selector query and scans the result into the given value.
func (tegb *Table01ForEntGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tegb.build.ctx, ent.OpQueryGroupBy)
	if err := tegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*Table01ForEntQuery, *Table01ForEntGroupBy](ctx, tegb.build, tegb, tegb.build.inters, v)
}

func (tegb *Table01ForEntGroupBy) sqlScan(ctx context.Context, root *Table01ForEntQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tegb.fns))
	for _, fn := range tegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tegb.flds)+len(tegb.fns))
		for _, f := range *tegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Table01ForEntSelect is the builder for selecting fields of Table01ForEnt entities.
type Table01ForEntSelect struct {
	*Table01ForEntQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tes *Table01ForEntSelect) Aggregate(fns ...AggregateFunc) *Table01ForEntSelect {
	tes.fns = append(tes.fns, fns...)
	return tes
}

// Scan applies the selector query and scans the result into the given value.
func (tes *Table01ForEntSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tes.ctx, ent.OpQuerySelect)
	if err := tes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*Table01ForEntQuery, *Table01ForEntSelect](ctx, tes.Table01ForEntQuery, tes, tes.inters, v)
}

func (tes *Table01ForEntSelect) sqlScan(ctx context.Context, root *Table01ForEntQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tes.fns))
	for _, fn := range tes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
